### ISSUE TITLE
Share flow ids between the node process and the setup script

### ISSUE THREAD

**Issue by joakin** [phuedx/micro-device-lab#2]
From irc review:

> I think it is worth sharing the profile ids between the node process and the bash script somehow https://github.com/phuedx/micro-device-lab/blob/dev/src/profiles.js#L8-L13 so that you don't have to implicitly keep them in sync the ids with the setup script ones.

I think the easiest way would be a script that exports the profiles and ids as environment variables, such script would get called at the beginning of [script/setup](https://github.com/phuedx/micro-device-lab/blob/dev/script/setup) and in [package.json](https://github.com/phuedx/micro-device-lab/blob/dev/package.json#L3) when `npm start`ing:

``` json
  "scripts": {
    "start": "./scripts/env && node index.js"
  }
```

``` diff
 cd "$(dirname "$0")/.."

+script/env
 script/bootstrap
```

Not exactly sure about that `script/env` would set. I know there's bash dictionaries but I'm not sure how those would be read in node with `process.env`.

Is there an easy way to load a JSON file into a bash script?

Any opinions?

**Comment by joakin** [comment]
I've found https://github.com/dominictarr/JSON.sh, we could have a json file with the profiles and profile data and read it in bash and do stuff with it.

Another option is converting `script/setup` to a node script with shebang, and then server and setup script can share a json file for example.

**Comment by phuedx** [comment]
> Another option is converting script/setup to a node script with shebang, and then server and setup script can share a json file for example.

That is my preference. Right now, my priority is a functioning UI, with developer happiness (including documentation) and flexibility a close second and third respectively.

**Comment by joakin** [comment]
Open to PR about this?

**Comment by phuedx** [comment]
> Open to PR about this?

Thanks for the offer but I'm hoping to take cues (and take the time to learn) from [joakin/stack](https://github.com/joakin/stack) – React, webpack, and material-ui.

**Comment by joakin** [comment]
@phuedx Sure! I think I wasn't clear enough, I was asking if you'd be interested in a PR about sharing profiles and IDs in setup and server.

**Comment by phuedx** [comment]
1470435 encodes the network throttling profiles in `profiles.json`. Converting `script/setup` to a Node.js script that reads from that file would be neato!

**Comment by phuedx** [comment]
@joakin I didn't know about `child_process.execSync` Iuntil 24 hours ago.
